package com.example.pse_appellointermedio

import android.app.Application
import android.util.Log
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import androidx.compose.runtime.getValue
import androidx.compose.runtime.neverEqualPolicy
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.SavedStateHandle
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancel

//ViewModel used to hold sequences, states and coroutines
//Used to make coroutines survive recomposition
class GameViewModel(application : Application, private val savedStateHandle: SavedStateHandle) : AndroidViewModel(application) {
    //Sequence inputted by the user
    var sequenceString by mutableStateOf("")
    //Sequence generated by the computer
    var proposedSequence by mutableStateOf("")
    //Length of the generated color sequence (in terms of number color initials, not actual string length)
    var sequenceLength by mutableIntStateOf(0)
    //Length so far of the inputted sequence
    var inputLength by mutableIntStateOf(0)

    //States
    //Only true if the app was killed by the
    var hasRestarted by mutableStateOf(false)
    var isPaused by mutableStateOf(false)
    //Acts as a mutex for receiving user input
    var isShowingSequence by mutableStateOf(false)
    var hasStartedGame by mutableStateOf(false)
    var hIndex by mutableStateOf<Int?>(null)
    var errorState by mutableStateOf(false)

    //Sound stuff
    val soundPlayer = SoundPlayer(application.applicationContext)
    fun playColorAudio(index : Int) {
        if(index in 0 .. 6) {
            soundPlayer.playSound(index)
        }
    }

    //SQL db
    val dm = DataManager(application.applicationContext)
    //Record list (to make the db entries be observable by Compose)
    var gamesList by mutableStateOf(dm.getGames(), policy = neverEqualPolicy())

    //Save state to recover activity when android kills the app to free resources
    //I decided to use savedStateHandle instead of sharedPreferences since
    //it's slightly easier to use and is meant for temporary state saving
    var userClosed : Boolean
        get() = savedStateHandle.get<Boolean>("userClosed") ?: false
        set(value) { savedStateHandle["userClosed"] = value }
    var seqString_save : String
        get() = savedStateHandle.get<String>("seqString_save") ?: ""
        set(value) { savedStateHandle["seqString_save"] = value }
    var propString_save : String
        get() = savedStateHandle.get<String>("propString_save") ?: ""
        set(value) { savedStateHandle["propString_save"] = value }
    var seqLength_save : Int
        get() = savedStateHandle.get<Int>("seqLength_save") ?: 0
        set(value) { savedStateHandle["seqLength_save"] = value }
    var inputLength_save : Int
        get() = savedStateHandle.get<Int>("inputLength_save") ?: 0
        set(value) { savedStateHandle["inputLength_save"] = value }
    var showSeq_save : Boolean
        get() = savedStateHandle.get<Boolean>("showSeq_save") ?: false
        set(value) { savedStateHandle["showSeq_save"] = value }
    var startGame_save : Boolean
        get() = savedStateHandle.get<Boolean>("startGame_save") ?: false
        set(value) { savedStateHandle["startGame_save"] = value }
    var pauseState_save : Boolean
        get() = savedStateHandle.get<Boolean>("pauseState_save") ?: false
        set(value) { savedStateHandle["pauseState_save"] = value }
    var errorState_save : Boolean
        get() = savedStateHandle.get<Boolean>("errorState_save") ?: false
        set(value) { savedStateHandle["errorState_save"] = value }

    //Starts coroutine for adding a color to the generated sequence and showing it all
    private var job : Job? = null
    fun startSequence() {
        job = viewModelScope.launch {
            //The delay here serves as a way to prevent the input sequence from being deleted as soon as it's typed out
            delay(500)
            inputLength = 0
            sequenceString = ""
            delay(200)

            isShowingSequence = true
            proposedSequence = addToRandomSequence(proposedSequence)
            val s = proposedSequence.replace(", ", "")
            sequenceLength++


            for (c in s) {
                //Stalls the coroutine (without blocking the thread) if game is paused
                waitIfPaused()
                //Sets color index to highlight
                hIndex = getIndexFromColor(c)
                playColorAudio(hIndex as Int)
                delay(600)
                hIndex = null
                delay(100)
            }
            isShowingSequence = false
        }
    }

    //Reads the generated sequence without adding any color
    fun readSequence() {
        viewModelScope.launch {
            inputLength = 0
            sequenceString = ""

            isShowingSequence = true
            val s = proposedSequence.replace(", ", "")
            for (c in s) {
                waitIfPaused()
                hIndex = getIndexFromColor(c)
                playColorAudio(hIndex as Int)
                delay(600)
                hIndex = null
                delay(100)
            }
            isShowingSequence = false
        }
    }

    //Stops coroutine
    fun stopSequence() {
        job?.cancel()
        job = null
        isShowingSequence = false
    }

    //Used to pause coroutine
    private suspend fun waitIfPaused() {
        while (isPaused) {
            //Without the delay the thread would be blocked
            delay(100)
        }
    }

    //Adds new color to the user's input sequence
    fun addAndCheckColor(i : Int) {
        if(!isShowingSequence && proposedSequence.isNotEmpty() && !errorState) {
            sequenceString = appendColorToSequence(i, sequenceString)
            inputLength++

            //Only here to prevent crashes if the input and the proposed sequences get out of sync
            if (sequenceString.length > proposedSequence.length) {
                errorState = true
                return
            }

            //If the partial string matches continue, otherwise go into error state
            if(sequenceString == proposedSequence.subSequence(0, sequenceString.length).toString()) {
                if(inputLength == sequenceLength)
                    startSequence()
                //Log.i("seq", "match")
            } else {
                //Error screen
                errorState = true
                //Log.i("seq", "mismatch")
            }
        }
    }

    //Adds record to the db and refreshes the compose observed record list
    fun addGame(errorIndex : Int, sequence : String) {
        dm.addGame(if(errorIndex>0) errorIndex else 0, sequence)
        gamesList = dm.getGames()

        resetState()
    }

    //State gets reset
    fun resetState() {
        inputLength = 0
        sequenceLength = 0
        sequenceString = ""
        proposedSequence = ""

        hasRestarted = false
        isShowingSequence = false
        hasStartedGame = false
        isPaused = false
        hIndex = null
        errorState = false
    }

    //Indicates whether the app was left in a state to be recovered or not when it was closed
    fun shouldRecover() : Boolean {
        return startGame_save && !userClosed
    }

    //Saves state to recover
    fun setRecoveryState() {
        seqString_save = sequenceString
        propString_save = proposedSequence
        seqLength_save = sequenceLength
        inputLength_save = inputLength
        showSeq_save = isShowingSequence
        startGame_save = hasStartedGame
        pauseState_save = isPaused
        errorState_save = errorState
    }

    //Sets back the app's state from the save
    fun loadRecoveryState() {
        userClosed = false
        sequenceString = seqString_save
        proposedSequence = propString_save
        sequenceLength = seqLength_save
        inputLength = inputLength_save
        isShowingSequence = showSeq_save
        hasStartedGame = startGame_save
        isPaused = pauseState_save
        errorState = errorState_save
        Log.i("seq", "loadRecoveryState: sequenceLength=$sequenceLength seqLength_save=$seqLength_save")
    }

    //Resets the save
    fun resetRecoveryState() {
        userClosed = false
        seqString_save = ""
        propString_save = ""
        seqLength_save = 0
        inputLength_save = 0
        showSeq_save = false
        startGame_save = false
        pauseState_save = false
        errorState_save = false
    }

    //Clean-up
    override fun onCleared() {
        super.onCleared()
        soundPlayer.release()
    }
}