package com.example.pse_appellointermedio

import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue

//ViewModel used to hold sequences, states and coroutines
//Used to make coroutines survive recomposition
class GameViewModel() : ViewModel() {
    //Sequence inputted by the user
    var sequenceString by mutableStateOf("")
    //Sequence generated by the computer
    var proposedSequence by mutableStateOf("")
    //Length of the generated color sequence (in terms of color initials, not actual string length)
    var sequenceLength by mutableIntStateOf(0)
    //Length so far of the inputted sequence
    var inputLength by mutableIntStateOf(0)

    //States
    var isPaused by mutableStateOf(false)
    //Acts as a mutex for receiving user input
    var isShowingSequence by mutableStateOf(false)
    var hasStartedGame by mutableStateOf(false)
    var hIndex by mutableStateOf<Int?>(null)
    var errorState by mutableStateOf(false)

    //Starts coroutine for adding a color to the generated sequence and showing it all
    fun startSequence(playColorAudio : (Int) -> Unit) {
        viewModelScope.launch {
            //The delay here serves as a way to prevent the input sequence from being deleted as soon as it's typed out
            delay(500)
            inputLength = 0
            sequenceString = ""
            delay(200)

            isShowingSequence = true
            proposedSequence = addToRandomSequence(proposedSequence)
            val s = proposedSequence.replace(", ", "")
            sequenceLength++

            for (c in s) {
                //Stalls the coroutine (without blocking the thread) if game is paused
                waitIfPaused()
                //Sets color index to highlight
                hIndex = getIndexFromColor(c)
                playColorAudio(hIndex as Int)
                delay(600)
                hIndex = null
                delay(200)
            }
            isShowingSequence = false
        }
    }

    //Used to pause coroutine
    private suspend fun waitIfPaused() {
        while (isPaused) {
            //Without the delay the thread would be blocked
            delay(100)
        }
    }

    //Adds color to user's sequence and checks for errors
    val addAndCheckColor : (Int, (Int) -> Unit) -> Unit = {i, playColorAudio ->
        if(!isShowingSequence && proposedSequence.isNotEmpty() && !errorState) {
            sequenceString = appendColorToSequence(i, sequenceString)
            inputLength++

            if(sequenceString == proposedSequence.subSequence(0, sequenceString.length).toString()) {
                if(inputLength == sequenceLength)
                    startSequence(playColorAudio)
                //Log.i("seq", "match")
            } else {
                //Error screen
                errorState = true
                //Log.i("seq", "mismatch")
            }
        }
    }
}